### ISSUE TITLE
Report packaged library

### ISSUE THREAD

**Issue by theamericanaccount** [kevinAlbs/libbase122#5]
Hello @kevinAlbs,

this is not actually an issue report.
I just wanted to thank you for your amazing work on this library, which of a build recipe has just been integrated in Life / DogeOS through the [Ur](https://github.com/themartiancompany/base122-ur), which of a binary package has just been released on the [Fur](https://github.com/themartiancompany/fur) and which has just been integrated in the Twitter (not X) app and soon in the EVM file system.

Keep up with the splendid work,
hopefully you're gonna receive a share of future profits anytime soon.

Cheers!

**Comment by theamericanaccount** [comment]
Oh btw that guy on reddit is a minus habens, suggesting your library doesn't pair well with compression algorithms, your encoder works great with zlib, but I guess you know already!

**Comment by kevinAlbs** [comment]
Glad to hear the project is useful. :)
